### ISSUE TITLE
Tag v4.2

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/force-lowest#1]
I just pushed a new commit on https://github.com/symfony/force-lowest/commit/ba8231511b04809e778fd3452c60d2caad93d02b

It can be tagged as v4.2 right now so that `composer create-project -s dev symfony/skeleton` works again.
See https://github.com/symfony/skeleton/blob/master/composer.json#L12

**Comment by fabpot** [comment]
Tagged as v4.2.0. Updated the release tool to take this into account next time.
